batch_size: 256
epochs: 15
lr: 0.00001
weight_decay: 0.0001
log_interval: 2
validation_interval: 1
val_log_interval: 1
lambda_param: 0.0051
preprocessor_type: All_types_shuffle_method
task_name: 'shuffle_method_matminer_dataset'
lr_gamma: 0.1
stepsize: 3
dataset:
  dataset_paths:
    KNN_ASYMMETRIC: 'Data_process/h5py_files/Matminer_all_KNN_ASYMMETRIC/matminer/5f6360b5449d4ed20471a56eb03cf1b6.h5'
    KNN_NonPeriodic: 'Data_process/h5py_files/Matminer_all_KNN_NonPeriodic/matminer/6d50fa659d7c81a97bb00394902fa922.h5'
    KNN_UnitCell: 'Data_process/h5py_files/Matminer_all_KNN_UnitCell/matminer/1a360b52d1e67cbd6c3774724106e98f.h5'
    Radi_ASYMMETRIC: 'Data_process/h5py_files/Matminer_all_Radi_ASYMMETRIC/matminer/656c199cdd61e9f5f64dae0732010bfb.h5'
    Radi_NonPeriodic: 'Data_process/h5py_files/Matminer_all_Radi_NonPeriodic/matminer/9894fb11c6fca850bec099673242cfdc.h5'
    Radi_UnitCell: 'Data_process/h5py_files/Matminer_all_Radi_UnitCell/matminer/0eed1d6ffe80db35bdcd8bff868efa75.h5'
    Voro_ASYMMETRIC: 'Data_process/h5py_files/Matminer_all_Voro_ASYMMETRIC/matminer/3e5ccee5a1607e5c5041b737509fc8f0.h5'
    Voro_NonPeriodic: 'Data_process/h5py_files/Matminer_all_Voro_NonPeriodic/matminer/2f7e6be4691734911c9c84f4371e2cbe.h5'
    Voro_UnitCell: 'Data_process/h5py_files/Matminer_all_Voro_UnitCell/matminer/912cacd9b291093f130d975c25cdf385.h5'
  with_voronoi_ridge_areas: False
dataloader:
  train_ratio: 0.95
  val_ratio: 0.05
  test_ratio: null
  num_workers: 8
  seed: 123

model_params:
  node_dim: 72
  node_expand_dim: 128
  edge_dim: 41 # 41 if no voronoi_area
  edge_expand_dim: 128
  MLP1_dim: 128
  MLP2_dim: 64
  fine_tune_classes: 64
  dimensionslist:
    - [128, 256, 128]
    - [256, 256, 128]
    - [256, 128, 128]